
# ============================================================
# Model Registration
# ============================================================

import json
import logging

import mlflow
import dagshub


# ============================================================
# DagsHub + MLflow configuration
# ============================================================

REPO_OWNER = "mayankkumar202001-svg"
REPO_NAME = "mylap_mlops_new"

dagshub.init(
    repo_owner=REPO_OWNER,
    repo_name=REPO_NAME,
    mlflow=True
)

mlflow.set_tracking_uri(
    f"https://dagshub.com/{REPO_OWNER}/{REPO_NAME}.mlflow"
)


# ============================================================
# Logging configuration
# ============================================================

logger = logging.getLogger("model_registration")
logger.setLevel(logging.DEBUG)

if not logger.handlers:

    console_handler = logging.StreamHandler()
    console_handler.setLevel(logging.DEBUG)

    file_handler = logging.FileHandler(
        "model_registration_errors.log"
    )
    file_handler.setLevel(logging.ERROR)

    formatter = logging.Formatter(
        "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    )

    console_handler.setFormatter(formatter)
    file_handler.setFormatter(formatter)

    logger.addHandler(console_handler)
    logger.addHandler(file_handler)


# ============================================================
# Load model information
# ============================================================

def load_model_info(file_path: str) -> dict:

    try:

        with open(file_path, "r") as file:
            model_info = json.load(file)

        logger.info(
            "Model information loaded from %s",
            file_path
        )

        return model_info

    except FileNotFoundError:

        logger.error(
            "Model information file not found: %s",
            file_path
        )

        raise

    except json.JSONDecodeError as e:

        logger.error(
            "Invalid JSON in %s: %s",
            file_path,
            e
        )

        raise

    except Exception as e:

        logger.error(
            "Error loading model information: %s",
            e
        )

        raise


# ============================================================
# Register model
# ============================================================

def register_model(
    model_name: str,
    model_info: dict
):

    try:

        # ----------------------------------------------------
        # Get model URI generated by MLflow 3.x
        # ----------------------------------------------------

        model_uri = model_info["model_uri"]

        logger.info(
            "Model URI: %s",
            model_uri
        )

        # ----------------------------------------------------
        # Register model
        # ----------------------------------------------------

        model_version = mlflow.register_model(
            model_uri=model_uri,
            name=model_name
        )

        logger.info(
            "Model '%s' version '%s' registered successfully.",
            model_name,
            model_version.version
        )

        return model_version

    except KeyError:

        logger.error(
            "'model_uri' not found in experiment_info.json"
        )

        raise

    except Exception as e:

        logger.exception(
            "Error during model registration: %s",
            e
        )

        raise


# ============================================================
# Main
# ============================================================

def main():

    try:

        # ----------------------------------------------------
        # Path generated by model_evaluation.py
        # ----------------------------------------------------

        model_info_path = (
            "mlops_project/reports/experiment_info.json"
        )

        # ----------------------------------------------------
        # Load experiment information
        # ----------------------------------------------------

        model_info = load_model_info(
            model_info_path
        )

        # ----------------------------------------------------
        # Registered model name
        # ----------------------------------------------------

        model_name = "my_model"

        # ----------------------------------------------------
        # Register model
        # ----------------------------------------------------

        register_model(
            model_name=model_name,
            model_info=model_info
        )

        logger.info(
            "Model registration completed successfully."
        )

    except Exception as e:

        logger.exception(
            "Failed to complete model registration: %s",
            e
        )

        raise


# ============================================================
# Entry point
# ============================================================

if __name__ == "__main__":
    main()
